---
version: '2.1'

services:
    idam-web-admin:
      image: hmctspublic.azurecr.io/idam/web-admin:latest
      environment:
        - JAVA_OPTS=-Xms128m -Xmx512m
        - STRATEGIC_SERVICE_URL=http://sidam-api:5000
      ports:
        - 8082:8080
      links:
        - sidam-api
      depends_on:
        - sidam-api

    idam-web:
      image: hmctspublic.azurecr.io/idam/web-public:latest
      environment:
        - STRATEGIC_SERVICE_URL=http://sidam-api:5000
        - IDAM_CONTINUE_URL_VALIDATOR_ENFORCE_TLS=false
        - JAVA_OPTS=-Xms128m -Xmx512m
      mem_limit: 256m
      memswap_limit: 0
      depends_on:
        sidam-api:
          condition: service_started
      healthcheck:
        disable: true
      ports:
        - 9002:8080

    sidam-api:
      image: hmctspublic.azurecr.io/idam/api:latest
      command: --wait-for-database 60
      environment:
        - JAVA_OPTS=-Xms128m -Xmx512m -Dlogging.level.uk.gov.hmcts=DEBUG
        - SPRING_DATASOURCE_URL=jdbc:postgresql://shared-db:5432/openidm?currentSchema=fridam
        - TESTING_SUPPORT_ENABLED=true
        - SPRING_MAIL_HOST=smtp-server
        - NOTIFY_API_KEY=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        - NOTIFY=false
        - REFORM_ENVIRONMENT=test
      mem_limit: 512m
      memswap_limit: 0
      depends_on:
        fr-am:
          condition: service_started
        fr-idm:
          condition: service_started
        shared-db:
          condition: service_started
      ports:
        - 5000:5000

    fr-am:
      image: "hmctsprivate.azurecr.io/idam/idam-fr-am:latest"
      environment:
        - JAVA_OPTS=-Xms128m -Xmx512m
      ports:
        - 8080:8080
        - 1389:1389
      depends_on:
        shared-db:
          condition: service_started

    fr-idm:
      image: "hmctsprivate.azurecr.io/idam/idam-fr-idm:latest"
      ports:
        - 18080:18080
        - 9010:9010
      environment:
        - JAVA_TOOL_OPTIONS=-Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=vm-ubuntu16 -Dcom.sun.management.jmxremote.rmi.port=9010
        - JAVA_OPTS=-Xms128m -Xmx512m
      depends_on:
        fr-am:
          condition: service_started
        shared-db:
          condition: service_started

    shared-db:
      image: "hmctsprivate.azurecr.io/idam/shared-db:latest"
      ports:
        - 5051:5432

    smtp-server:
      image: mailhog/mailhog
      mem_limit: 32m
      memswap_limit: 0
      ports:
        - 1025:1025

    service-auth-provider-api:
      image: hmctspublic.azurecr.io/rpe/service-auth-provider:latest
      environment:
        - SERVER_PORT=8080
        - JAVA_OPTS=-Xms8m -Xmx256m -Djava.security.egd=file:/dev/./urandom -XX:MaxMetaspaceSize=128m
        - JWT_KEY=wThK0f0/lh3FlxFcL4xUWDMI5C1J9KyQBgXV4wseh1e5J1uYJIjvTvArHxQDrYoHJ23xFxjHkOnvNbR5dXRoxA==
        - MICROSERVICEKEYS_BULK_SCAN_PROCESSOR=AAAAAAAAAAAAAAAA
        - MICROSERVICEKEYS_BULK_SCAN_PROCESSOR_TESTS=AAAAAAAAAAAAAAAA
        - MICROSERVICEKEYS_BULK_SCAN_ORCHESTRATOR=AAAAAAAAAAAAAAAA
        - MICROSERVICEKEYS_EM_GW=AAAAAAAAAAAAAAAA
        - MICROSERVICEKEYS_CCD_DATA=AAAAAAAAAAAAAAAA
        - MICROSERVICEKEYS_CCD_DEFINITION=AAAAAAAAAAAAAAAA
        - MICROSERVICEKEYS_CCD_GW=AAAAAAAAAAAAAAAA
        - TESTING_SUPPORT_ENABLED=true
      mem_limit: 512m
      memswap_limit: 0
      healthcheck:
        disable: true
      ports:
        - 4552:8080

    shared-database-v10:
      image: postgres:18.0-alpine
      command: postgres -c 'max_connections=250'
      volumes:
        - ./docker/database/init-db-v10.sh:/docker-entrypoint-initdb.d/init-db.sh
        - shared-database-data-v10:/var/lib/postgresql/data
      healthcheck:
        test: psql -c 'select 1' -d postgres -U postgres
        retries: 40
      mem_limit: 320m
      memswap_limit: 0
      ports:
        - 5052:5432

    ccd-user-profile-api:
        image: hmctspublic.azurecr.io/ccd/user-profile-api:latest
        environment:
          - JAVA_OPTS=-Xms8m -Xmx256m -Djava.security.egd=file:/dev/./urandom -XX:MaxMetaspaceSize=128m
          - USER_PROFILE_DB_HOST=shared-database-v10
          - USER_PROFILE_DB_PORT=5432
          - USER_PROFILE_DB_NAME=ccd_user_profile
          - USER_PROFILE_DB_USERNAME=ccd_user_profile
          - USER_PROFILE_DB_PASSWORD=ccd_user_profile
          - USER_PROFILE_S2S_AUTHORISED_SERVICES=ccd_data,ccd_definition
          - IDAM_S2S_URL=http://service-auth-provider-api:8080
          - REFORM_SERVICE_NAME=ccd-user-profile-api
          - REFORM_TEAM=ccd
          - REFORM_ENVIRONMENT=local
          - AZURE_APPLICATIONINSIGHTS_INSTRUMENTATIONKEY=fake-key
          - USER_PROFILE_DB_USE_SSL=false
        mem_limit: 512m
        memswap_limit: 0
        depends_on:
          shared-database-v10:
            condition: service_healthy
          service-auth-provider-api:
            condition: service_started
        healthcheck:
          disable: true
        ports:
          - 4453:4453

    ccd-definition-store-api:
      # todo: this version is a patch for NPE spreadsheet parser inspected while importing definitions
      # once it is introduced in latest version can be reverted to just `hmcts/ccd-definition-store-api:latest`
      image: hmctspublic.azurecr.io/ccd/definition-store-api:pr-402
      environment:
        - JAVA_OPTS=-Xms8m -Xmx256m -Djava.security.egd=file:/dev/./urandom -XX:MaxMetaspaceSize=128m
        - DEFINITION_STORE_DB_HOST=shared-database-v10
        - DEFINITION_STORE_DB_PORT=5432
        - DEFINITION_STORE_DB_USERNAME=ccd_definition_store
        - DEFINITION_STORE_DB_PASSWORD=ccd_definition_store
        - SPRING_DATASOURCE_URL=jdbc:postgresql://shared-database-v10:5432/ccd_definition_store
        - DEFINITION_STORE_IDAM_KEY=AAAAAAAAAAAAAAAA
        - DEFINITION_STORE_S2S_AUTHORISED_SERVICES=ccd_data,bulk_scan_orchestrator,ccd_gw
        - USER_PROFILE_HOST=http://ccd-user-profile-api:4453
        - IDAM_USER_URL=http://sidam-api:5000
        - IDAM_S2S_URL=http://service-auth-provider-api:8080
        - REFORM_SERVICE_NAME=ccd-definition-store-api
        - REFORM_TEAM=ccd
        - REFORM_ENVIRONMENT=local
        - APPINSIGHTS_INSTRUMENTATIONKEY=fake-key
      mem_limit: 512m
      memswap_limit: 0
      depends_on:
        ccd-user-profile-api:
          condition: service_started
        sidam-api:
          condition: service_started
        service-auth-provider-api:
          condition: service_started
        shared-database-v10:
          condition: service_healthy
      healthcheck:
        disable: true
      ports:
        - 4451:4451

    ccd-data-store-api:
      image: hmctspublic.azurecr.io/ccd/data-store-api:latest
      environment:
        - JAVA_OPTS=-Xms8m -Xmx256m -Djava.security.egd=file:/dev/./urandom -XX:MaxMetaspaceSize=128m
        - DATA_STORE_DB_HOST=shared-database-v10
        - DATA_STORE_DB_PORT=5432
        - DATA_STORE_DB_USERNAME=ccd_data_store
        - DATA_STORE_DB_PASSWORD=ccd_data_store
        - DATA_STORE_IDAM_KEY=AAAAAAAAAAAAAAAA
        - SPRING_DATASOURCE_URL=jdbc:postgresql://shared-database-v10:5432/ccd_data_store?stringtype=unspecified
        - DATA_STORE_TOKEN_SECRET=sdsadahjsadhgaskjhdhasghgkjasd
        - DATA_STORE_S2S_AUTHORISED_SERVICES=bulk_scan_orchestrator,ccd_gw
        - DEFINITION_STORE_HOST=http://ccd-definition-store-api:4451
        - USER_PROFILE_HOST=http://ccd-user-profile-api:4453
        - IDAM_USER_URL=http://sidam-api:5000
        - IDAM_S2S_URL=http://service-auth-provider-api:8080
        - REFORM_SERVICE_NAME=ccd-data-store-api
        - REFORM_TEAM=ccd
        - REFORM_ENVIRONMENT=local
        - APPINSIGHTS_INSTRUMENTATIONKEY=fake-key
        - CCD_DM_DOMAIN=http://dm-store:4460
      mem_limit: 512m
      memswap_limit: 0
      depends_on:
        ccd-user-profile-api:
          condition: service_started
        dm-store:
          condition: service_started
        sidam-api:
          condition: service_started
        service-auth-provider-api:
          condition: service_started
        shared-database-v10:
          condition: service_healthy
      healthcheck:
        disable: true
      ports:
       - 4452:4452

    ccd-importer:
      build:
        context: docker/ccd-definition-import
      image: hmcts/bulk-scan-ccd-importer
      environment:
        WAIT_HOSTS: ccd-user-profile-api:4453, ccd-definition-store-api:4451, service-auth-provider-api:8080, ccd-api-gateway:3453, sidam-api:5000
        VERBOSE: ${VERBOSE:-false}
        WAIT_HOSTS_TIMEOUT: 300
        IMPORTER_USERNAME: ccd-importer@server.net
        IMPORTER_PASSWORD: Password12
        IDAM_URI: http://sidam-api:5000
        REDIRECT_URI: http://localhost:3000/receiver
        CCD_ROLE: caseworker-bulkscan
        BULK_SCAN_ORCHESTRATOR_BASE_URL: http://host.docker.internal:8582
      depends_on:
        sidam-api:
          condition: service_started
        ccd-definition-store-api:
          condition: service_started
      volumes:
        - ./docker/ccd-definition-import/data:/definitions
        - ./docker/ccd-definition-import/scripts:/scripts

    idam-importer:
      build:
        context: docker/idam-importer
      environment:
        IDAM_API_URL: http://sidam-api:5000
        IDAM_ADMIN_USER: ${IDAM_USERNAME}
        IDAM_ADMIN_PASSWORD: ${IDAM_PASSWORD}
        WAIT_HOSTS: sidam-api:5000
        WAIT_HOSTS_TIMEOUT: 300
      depends_on:
        sidam-api:
          condition: service_started

    ccd-case-management-web:
      image: hmctspublic.azurecr.io/ccd/case-management-web:latest
      environment:
        - IDAM_LOGIN_URL=http://localhost:9002/login
        - CCD_GATEWAY_BASE_URL=http://localhost:3453
        - CCD_ACTIVITY_BASE_URL=http://localhost:3455
        - DM_URL=http://localhost:3453/documents
        - DM_URL_REMOTE=http://dm-store:4460/documents
        - OAUTH2_CLIENT_ID=ccd_gateway
      mem_limit: 256m
      memswap_limit: 0
      depends_on:
        ccd-api-gateway:
          condition: service_started
        idam-web:
          condition: service_started
      healthcheck:
        disable: true
      ports:
        - 3451:3451

    ccd-api-gateway:
      image: hmctspublic.azurecr.io/ccd/api-gateway-web:latest
      environment:
        - IDAM_BASE_URL=http://sidam-api:5000
        - IDAM_USER_URL=http://sidam-api:5000
        - IDAM_LOGOUT_URL=http://localhost:9002/login/logout
        - IDAM_OAUTH2_CLIENT_ID=ccd_gateway
        - IDAM_OAUTH2_CLIENT_SECRET=123456
        - IDAM_OAUTH2_TOKEN_ENDPOINT=http://sidam-api:5000/oauth2/token
        - IDAM_S2S_URL=http://service-auth-provider-api:8080
        - IDAM_SERVICE_KEY=AAAAAAAAAAAAAAAA
        - IDAM_SERVICE_NAME=ccd_gw
        - PROXY_AGGREGATED=http://ccd-data-store-api:4452
        - PROXY_DATA=http://ccd-data-store-api:4452
        - PROXY_DEFINITION_IMPORT=http://ccd-definition-store-api:4451
        - PROXY_DOCUMENT_MANAGEMENT=http://dm-store:4460
        - PROXY_DEFINITION_DATA=http://ccd-definition-store-api:4451/api/data
        - PROXY_DEFINITION_DISPLAY=http://ccd-definition-store-api:4451/api/display
        - APPINSIGHTS_INSTRUMENTATIONKEY=fake-key
      mem_limit: 256m
      memswap_limit: 0
      depends_on:
        ccd-user-profile-api:
          condition: service_started
        ccd-definition-store-api:
          condition: service_started
        ccd-data-store-api:
          condition: service_started
      healthcheck:
        disable: true
      ports:
        - 3453:3453

    dm-store:
      image: hmctspublic.azurecr.io/dm/store:latest
      command: --wait-for-database 30
      environment:
        - JAVA_OPTS=-Xms8m -Xmx256m -Djava.security.egd=file:/dev/./urandom -XX:MaxMetaspaceSize=128m
        - SERVER_PORT=4460
        - SPRING_DATASOURCE_URL=jdbc:postgresql://shared-database-v10:5432/evidence
        - SPRING_DATASOURCE_USERNAME=evidence
        - SPRING_DATASOURCE_PASSWORD=evidence
        - IDAM_USER_BASE_URI=http://sidam-api:5000
        - IDAM_S2S_BASE_URI=http://service-auth-provider-api:8080
        - S2S_NAMES_WHITELIST=ccd_gw,cmc,bulk_scan_orchestrator,ccd_data,bulk_scan_processor
        - http_proxy=
        - https_proxy=
        - no_proxy=
        - ROOT_APPENDER=CONSOLE
        - REFORM_SERVICE_TYPE=java
        - REFORM_SERVICE_NAME=dm-store
        - REFORM_TEAM=evidence
        - REFORM_ENVIRONMENT=docker
        - ENABLE_DELETE=true
        - ENABLE_IDAM_HEALTH_CHECK=false
        - ENABLE_METADATA_SEARCH=true
        - ENABLE_DOCUMENT_AND_METADATA_UPLOAD=false
        - ENABLE_FOLDER_API=true
        - ENABLE_TTL=true
        - ENABLE_THUMBNAIL=true
        - DM_MULTIPART_WHITELIST=image/jpeg,application/pdf,image/tiff,image/png,image/bmp,text/plain,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.wordprocessingml.template,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.openxmlformats-officedocument.spreadsheetml.template,application/vnd.ms-powerpoint,application/vnd.openxmlformats-officedocument.presentationml.presentation,application/vnd.openxmlformats-officedocument.presentationml.template,application/vnd.openxmlformats-officedocument.presentationml.slideshow
        - DM_MULTIPART_WHITELIST_EXT=.jpg,.jpeg,.bmp,.tif,.tiff,.png,.pdf,.txt,.doc,.dot,.docx,.dotx,.xls,.xlt,.xla,.xlsx,.xltx,.xlsb,.ppt,.pot,.pps,.ppa,.pptx,.potx,.ppsx
        - MAX_FILE_SIZE=500MB
        - MAX_ACTIVE_DB_CONNECTIONS=10
        - ENDPOINTS_HEALTH_SENSITIVE=false
        - ENDPOINTS_INFO_SENSITIVE=false
        - CASE_WORKER_ROLES=caseworker-sscs
      depends_on:
        sidam-api:
          condition: service_started
        service-auth-provider-api:
          condition: service_started
      ports:
        - 4460:4460

volumes:
  shared-database-data-v10:
